### ISSUE TITLE
Schema feedback

### ISSUE THREAD

**Issue by kandersolar** [cwhanse/ivcurves#12]
A few things I noticed about the schema and test cases:
- The test case json files include `Temperature` for each IV curve, but that's not included in the schema
- The test case json files set `Datetime` to the empty string, which I think is not a valid value for the schema's `date-time` format
- Consider restricting `Sweep direction` to particular values (e.g. `"forward"`)
- Seems a bit strange to have `cells_in_series` specified next to the actual voltage and current values at the IV curve level

Note that the first two items also apply to the json files in https://github.com/pvlib/pvlib-python/pull/1573.

**Comment by cwhanse** [comment]
Let's also add `Serial Number`, `Model`, and rename `Sandia ID` to `Module ID`. We can move `cells_in_series` up into the block with `Manufacturer`. 

I don't know if we could enumerate all the needed values for `Sweep direction`. Some tracers will go both directions and then combine the values.

**Comment by cwhanse** [comment]
And add a `Description` field for the set of IV curves.

**Comment by cwhanse** [comment]
Consider adding `diode_voltage` to each IV curve (`voltage` + `series_resistance` * `current`). This may apply for synthetic curves where `series_resistance` is known, but not for measured curves.
