### ISSUE TITLE
Change to exact value for elementary charge

### ISSUE THREAD

**Issue by cwhanse** [cwhanse/ivcurves#20]
We left off the [last digit.](https://github.com/cwhanse/ivcurves/blob/09caa633c98b28891d84a56ae5d848b12920bf82/ivcurves/utils.py#L38) Should be 1.602176634×10−19

https://www.bipm.org/en/publications/si-brochure/

**Comment by cwhanse** [comment]
@reepoi do you want me to make this change?

**Comment by reepoi** [comment]
No, I can make a pull request for it soon. I will also continue to monitor and update the other pull requests I have open until they are closed.
