### ISSUE TITLE
Cells in series for test case 1?

### ISSUE THREAD

**Issue by williamhobbs** [cwhanse/ivcurves#38]
Should this be 72 cells? 

`case1.json` has `"cells_in_series": 72,`

https://github.com/cwhanse/ivcurves/blob/d5ae217596a7a1638e5f7570d3273b9d7c762ba4/docs/sphinx/source/test_cases.rst?plain=1#LL9C65-L9C132

**Comment by cwhanse** [comment]
Yes it should be 72, thanks!
